services:
  - type: web
    name: catalog-feed
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: catalog-db
          property: connectionString
      - key: AUTH_USERNAME
        value: admin
      - key: AUTH_PASSWORD
        generateValue: true

databases:
  - name: catalog-db
    databaseName: catalog
    user: catalog_user
    plan: free 